'use client';

import { useState } from 'react';
import { Copy, Check, RefreshCw } from 'lucide-react';
import { PatientActivationBadge } from './PatientActivationBadge';
import { Button } from '@/components/ui/Button';
import { showToast } from '@/components/ui/Toaster';

type ActivationData = {
  status: 'activated' | 'pending' | 'expired';
  code: string | null;
  generated_at: string | null;
  used_at: string | null;
  expires_at: string | null;
  generated_by_practitioner_id: string | null;
};

type PatientCodeSectionProps = {
  activation: ActivationData;
  practitionerName: string | null;
  patientId: string;
};

function formatDate(dateString: string | null): string {
  if (!dateString) return '—';
  return new Date(dateString).toLocaleDateString('fr-FR', {
    day: '2-digit',
    month: '2-digit',
    year: 'numeric',
    hour: '2-digit',
    minute: '2-digit',
  });
}

export function PatientCodeSection({
  activation,
  practitionerName,
  patientId,
}: PatientCodeSectionProps) {
  const [copied, setCopied] = useState(false);
  const [regenerating, setRegenerating] = useState(false);
  const [showConfirm, setShowConfirm] = useState(false);

  async function copyCode() {
    if (!activation.code) return;
    try {
      await navigator.clipboard.writeText(activation.code);
      setCopied(true);
      setTimeout(() => setCopied(false), 2000);
    } catch {
      showToast.error('Impossible de copier le code.');
    }
  }

  async function handleRegenerate() {
    setRegenerating(true);
    try {
      // Regenerate invitation code would typically be a POST to the backend
      // For now, show a placeholder
      showToast.info('Fonctionnalite de regeneration en cours de developpement.');
      setShowConfirm(false);
    } catch {
      showToast.error('Erreur lors de la regeneration du code.');
    } finally {
      setRegenerating(false);
    }
  }

  return (
    <div className="rounded-lg border border-slate-200 bg-white p-5">
      <h3 className="text-base font-semibold text-slate-800 mb-4">
        Code d&apos;activation
      </h3>

      <div className="space-y-3">
        {/* Code display */}
        <div className="flex items-center gap-3">
          <div className="text-sm text-slate-500">Code :</div>
          <div className="flex items-center gap-2">
            <code className="rounded bg-slate-100 px-3 py-1.5 text-sm font-mono font-medium text-slate-800">
              {activation.code ?? '—'}
            </code>
            {activation.code && (
              <button
                onClick={copyCode}
                className="rounded p-1 text-slate-400 hover:bg-slate-100 hover:text-slate-600 transition-colors"
                title="Copier le code"
              >
                {copied ? (
                  <Check className="h-4 w-4 text-emerald-500" />
                ) : (
                  <Copy className="h-4 w-4" />
                )}
              </button>
            )}
          </div>
        </div>

        {/* Status */}
        <div className="flex items-center gap-3">
          <div className="text-sm text-slate-500">Statut :</div>
          <PatientActivationBadge status={activation.status} />
        </div>

        {/* Generated date */}
        <div className="flex items-center gap-3">
          <div className="text-sm text-slate-500">Genere le :</div>
          <div className="text-sm text-slate-800">{formatDate(activation.generated_at)}</div>
        </div>

        {/* Used date */}
        <div className="flex items-center gap-3">
          <div className="text-sm text-slate-500">Utilise le :</div>
          <div className="text-sm text-slate-800">{formatDate(activation.used_at)}</div>
        </div>

        {/* Expires date */}
        {activation.expires_at && (
          <div className="flex items-center gap-3">
            <div className="text-sm text-slate-500">Expire le :</div>
            <div className="text-sm text-slate-800">{formatDate(activation.expires_at)}</div>
          </div>
        )}

        {/* Generated by */}
        <div className="flex items-center gap-3">
          <div className="text-sm text-slate-500">Genere par :</div>
          <div className="text-sm text-slate-800">{practitionerName ?? '—'}</div>
        </div>

        {/* Regenerate button */}
        {(activation.status === 'pending' || activation.status === 'expired') && (
          <div className="pt-3 border-t border-slate-100">
            {!showConfirm ? (
              <Button
                variant="outline"
                size="sm"
                onClick={() => setShowConfirm(true)}
                icon={<RefreshCw className="h-3.5 w-3.5" />}
              >
                Regenerer le code
              </Button>
            ) : (
              <div className="rounded-lg bg-amber-50 border border-amber-200 p-3">
                <p className="text-sm text-amber-800 mb-3">
                  L&apos;ancien code sera invalide. Confirmer la regeneration ?
                </p>
                <div className="flex gap-2">
                  <Button
                    variant="primary"
                    size="sm"
                    className="bg-amber-600 hover:bg-amber-700"
                    onClick={handleRegenerate}
                    loading={regenerating}
                  >
                    Confirmer
                  </Button>
                  <Button
                    variant="ghost"
                    size="sm"
                    onClick={() => setShowConfirm(false)}
                  >
                    Annuler
                  </Button>
                </div>
              </div>
            )}
          </div>
        )}
      </div>
    </div>
  );
}
